baseURL = "http://www.litylang.org"
languageCode = "en-us"
title = "Documentation for litylang"
theme = "hugo-theme-learn"
showVisitedLinks = false
enableRobotsTXT = true

[Languages]
[Languages.en]
title = "The Lity Language and Virtual Machine for Smart Contracts"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Lity source"
url = "https://github.com/CyberMiles/lity"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-file'></i> Lity docs"
url = "http://lity.readthedocs.io/"
weight = 11

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> libENI source"
url = "https://github.com/CyberMiles/libeni"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-file'></i> libENI docs"
url = "http://libeni.readthedocs.io/"
weight = 13

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> CyberMiles source"
url = "https://github.com/CyberMiles/travis"
weight = 14

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-file'></i> CyberMiles docs"
url = "http://travis.readthedocs.io/"
weight = 15

