baseURL = "https://lity.org"
languageCode = "en-us"
title = "Litylang"
theme = "hugo-theme-learn"
# publishDir = "docs"


[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/CyberMiles/lity"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "credits"
weight = 30